# Generated by Django 4.2.20 on 2025-04-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
